const images = {
    imgBf1: require('./imgBf1.png'),
    imgBf2: require('./imgBf2.png'),
    imgAt1: require('./imgAt1.png'),
    imgAt2: require('./imgAt2.png'),
    imgAt3: require('./imgAt3.png'),
    imgAt4: require('./imgAt4.png'),
    imgAt5: require('./imgAt5.png'),
    imgAt6: require('./imgAt6.png'),
    dad: require('./dad.png'),
    mom: require('./mom.png'),
    avtCmt: require('./avt-cmt.png'),
    camera: require('./camera.png'),
    setting: require('./setting-2.png'),
    bgEvent: require('./bg-event.png'),
    icClose: require('./icClose.png'),
    icFb: require('./icFb.png'),
    icSms: require('./sms.png'),
    icGg: require('./google.png'),
    icLogout: require('./logout.png'),
    icInputDad: require('./in_bgDad.png'),
    icInputMom: require('./in_bgMom.png'),
    icDownLoad: require('./ic_download.png'),
    icHeart: require('./ic-heart.png'),
    icUpload: require('./ic_upload.png'),
    machineImage: require('./machineImg.png'),
    uploadImage: require('./upload-Image.png'),
}

export default images;